version: '3.6'
services:
  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: 'postgres:11-alpine'
    restart: always
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
  backend:
    build: x2048/.
    command: mix do ecto.create, phx.server
    depends_on:
      - db
    ports:
      - '4000:4000'
    volumes:
      - ./x2048/config:/app/config:cached
      - ./x2048/lib:/app/lib:cached
      - ./x2048/priv:/app/priv:cached
      - ./x2048/test:/app/test:cached
  frontend:
    build: x2048-ui/.
    command: yarn serve
    depends_on:
      - backend
    ports:
      - '8080:8080'
    volumes:
      - './x2048-ui/src:/app/src:cached'
volumes:
  pgdata:
